name: shipengine-java CD

on:
  push:
    branches:
      - main


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: shipengine

      - uses: actions/checkout@v2.5.0
          
      - name: Build with Maven
        run: mvn clean compile -Dmaven.test.skip=true && mvn package -Dmaven.test.skip=true && mvn verify -Dmaven.test.skip=true
        
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
          
      - name: Setup Java
        uses: actions/setup-java@v3.6.0
        with:
          java-version: "11"
          architecture: x64
          distribution: "adopt"
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_USERNAME # env variable for username in deploy
          server-password: OSSRH_TOKEN # env variable for token in deploy
      
      - name: Publish package to Maven Central
        run: |
          mvn -X --batch-mode deploy -Dmaven.test.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
