name: shipengine-java CD

on:
  push:
    branches:
      - main


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: shipengine

      - uses: actions/checkout@v2.5.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          architecture: x64
          distribution: "adopt"
          
      - name: Build with Maven
        run: mvn clean compile -Dmaven.test.skip=true && mvn package -Dmaven.test.skip=true && mvn verify -Dmaven.test.skip=true
        
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
          
      - name: Setup Maven central
        uses: actions/setup-java@v3.6.0
        with:
          java-version: "11"
          architecture: x64
          distribution: "adopt"
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_USERNAME # env variable for username in deploy
          server-password: OSSRH_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE  # env variable for GPG private key passphrase
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      
      - name: Publish package to Maven Central
        run: |
          mvn -X deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
