name: shipengine-java CD

on:
  push:
    branches:
      - main


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: shipengine

      # Checkout code if release was created
      - uses: actions/checkout@v2.5.0
        if: ${{ steps.release.outputs.release_created }}

      # Setup Java and deploy if a release was created
      - name: Setup Java
        uses: actions/setup-java@v3.6.0
        with:
          java-version: "11"
          architecture: x64
          distribution: "adopt"
          cache: 'maven'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_USERNAME # env variable for username in deploy
          server-password: OSSRH_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE  # env variable for GPG private key passphrase

      - name: Publish package to Maven
        run: |
          mvn --batch-mode deploy -Dmaven.test.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        if: ${{ steps.release.outputs.release_created }}
