name: shipengine-java CD

on:
  push:
    branches:
      - main


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: shipengine
        if: ${{ steps.release.outputs.release_created }}

      # Checkout code if release was created
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      # Setup Java and deploy if a release was created
      - name: Setup Java
        uses: actions/setup-java@v2.3.0
        with:
          java-version: "11"
          architecture: x64
          distribution: "adopt"
          server-id: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package to Maven
        run: |
          mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
