name: shipengine-java CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "1.8"
          - "9.0"
          - "10.0"
          - "11.0"
          - "12.0"
          - "13.0"

    steps:
      - uses: actions/checkout@master

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64

      - name: Lint the code
        run: mvn checkstyle:checkstyle

      - name: Run test suite
        run: mvn test
