name: shipengine-java CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-18.04
        java-version:
          - "11"
          - "12"
          - "13"

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK v${{ matrix.java-version }} for x64
        uses: actions/setup-java@v2.3.0
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
          distribution: "adopt"
          server-id: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Lint the code
        run: |
          mvn --quiet checkstyle:check

      - name: Run test suite
        run: |
          mvn --quiet clean test jacoco:report coveralls:report -D repoToken=${{ secrets.COVERALLS_TOKEN }}
